branches:
  only:
  - master

language: objective-c
osx_image: xcode8.3

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated carthage || brew upgrade carthage

install:
  - pod install
  - cd Example
  - carthage update
  - cd ..

script:
  - ./scripts/prepare_ios_env.sh
  - ./scripts/build.sh

after_success:
  - ruby scripts/createManifest.rb YouboraAVPlayerAdapter AVPlayer
  - ruby scripts/make_deployable.rb
  - ruby scripts/deploy_to_qa.rb

after_failure:
  - cat -n ~/Library/Logs/scan/*

env:
  - QA_KNOWN_HOSTS="qa-smartplugin.youbora.com,81.171.21.12 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBM6lBT/mNpS5Sl2GtOiZiWsMr1XB+tluRmakhEyjPtOjQRjbP4Z/D9+yK0Iy5v99pecazEDuigHh5BZ2v3zWYUw="
