branches:
  only:
  - master

language: objective-c
osx_image: xcode8.3

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated carthage || brew upgrade carthage

install:
  - pod install
  - cd Example
  - carthage update
  - cd ..

script:
  - ./scripts/prepare_ios_env.sh
  - ./scripts/build.sh

after_success:
  - ruby scripts/createManifest.rb
  - ruby scripts/make_deployable.rb
  - ruby scripts/deploy_to_qa.rb

after_failure:
  - cat -n ~/Library/Logs/scan/*

