branches:
  only:
  - master

language: objective-c
osx_image: xcode8.3

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated carthage || brew upgrade carthage

install:
  - pod install
  - cd Example
  - carthage update
  - cd ..

script:
  - ./scripts/prepare_ios_env.sh
  - ./scripts/build.sh

after_success:
  - ruby scripts/createManifest.rb YouboraAVPlayerAdapter
  - ruby scripts/make_deployable.rb
  - ruby scripts/deploy_to_qa.rb

after_failure:
  - cat -n ~/Library/Logs/scan/*

env:
  global:
  # QA_KNOWN_HOSTS
    secure: pRp6TGAEKNnbHNgtSR87x02Bovda0f1VoI/wmkqeNO0rb0pPkBBqXK8sJ/E1OAYlYi8ITcy42atJIZ1KrsgO0NFpkdJdaKKpPtj72boMEp5HvRU7rXsLEXjodsIdegw8+JvFWXr+7In0MdlknCb/QwZF07SYdlYpJmsCbhgDcR5ZnvxGruwtyBESJoK1HkYpDCHvyUinbU257iJ5g/3LF78UhUH+Y3ZZXE9ce4G85as0EhV4sQ/guXa35cbp2V8Bbv8pvDMHTkrBxDuU7XRSM/JGsVYtGYGd/6A9vBBodXs+UTCGQDxiRl13FW02EIeN+wHYSyN72aNWWJ6gHOTIzKk38919PWX8KbOTj3t/x3SLuW+r7fd6VfZq7xAXZ2GZT4FXhaYeby6MgHgPZDnWhFaS+ZyCflx8ED8H5K+ycBbQNCBYLWo1tUP6w0H4kc6vvm1/BOaobVggdMj9nTV/4RKmDQq1Ohxv+m7eQxJFe8eDpxGOhmoB7Qlyd3xmzYcIwp4nNk84d1Oq4OYOaQFLJdvizsr9kNvfivrh3VW0x8gL/FHpwcVbW+uAzNftKiB1L187XXIMGcjUio1fRF/JXOQn2znzEU7G1W8V9T9GeGBJMwfIqSercdmRjAemUde3hVgcaG0/2UlqXcRio84RpfYhWJhi1xNLQ+f+GbZQ7t0=


