# Uncomment the next line to define a global platform for your project
workspace 'AVPlayerSampleP2P.xcworkspace'

def generic_pods
  pod 'YouboraLib'
  pod 'AVPlayerDNAPlugin'
end

target 'YouboraAVPlayerAdapter' do
  project '../../YouboraAVPlayerAdapter.xcodeproj'
  platform :ios, '10.2'
  use_frameworks!

  generic_pods
end

target 'AVPlayerP2PSample' do
  platform :ios, '10.2'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVPlayerSample
  generic_pods
  pod 'YouboraConfigUtils'
end
